#!/bin/bash
#
# list livebox deconnections date time
#
usage() {
  name=`basename "$0"`
  cat << EOF
usage: $name [filename]

This script returns the deconnection times as stored in the log file.

If filename isn't specified, it uses the standard input as input (cat filename | $name)
EOF
}
if [ $# -gt 1 ]; then
  usage
  exit 1
fi

if [ $# -eq 1 ]; then
  file=$1
  if [ ! -f $file ]; then
    echo "File $file doesn't exist"
    usage
    exit 1
  fi
fi
cut -d ';' -f 16,17 $file | awk '
BEGIN{last_timestamp = 0; nbdisconnections=0; last_start=""}
{ 
  if (match($0, /(.*);(.*)/, a)) {
    new_start = a[2]
    if (length(a[1]) > 0) {
      last_duration=a[1]
    }
    if (match(a[2], /.*, (.*)/, b)) {
      since=b[1]
      hour=strtonum(substr(since, 0, 2))
      min=strtonum(substr(since, 4, 2))
      sec=strtonum(substr(since, 7, 2))
      new_timestamp=hour*3600+min*60+sec
      if (last_start=="") {
        last_start = new_start
        last_timestamp = new_timestamp
      }
      # detect disconnect, we have a new start timestamp
      # start time is precise up to one second
      if (new_timestamp - last_timestamp > 1) {
        last_timestamp = new_timestamp
        print "Start: " last_start " Duration: " last_duration
        last_duration=""
        last_start = new_start
        nbdisconnections++
      }
    }
  }
}
END {
  print "Start: " last_start " Duration: " last_duration
  print "Nb disconnections: " nbdisconnections
}'

