#!/bin/bash
HOST=192.168.1.1
USER=root
PASSWORD=1234

type -P expect &>/dev/null || { echo "I require expect but it's not installed. Aborting." >&2; exit 1; }

expect << EOF
set timeout 20
spawn telnet $HOST
expect "login: "
send "$USER\n"
expect "Password: "
send "$PASSWORD\r"
expect "*\$ "
send "adsl\r"
expect "*\$ "
send "mon\r"
expect "*\$ "
send "exit\r"
expect "*\$ "
send "exit\r"
expect eof
exit
EOF
