#!/bin/bash
#
# list livebox deconnections date time
#
dir=`dirname $0`
usage() {
  name=`basename "$0"`
  cat << EOF
usage: $name [filename]

This script returns the deconnection times as stored in the log file.

If filename isn't specified, it uses the standard input as input (cat filename | $name)
EOF
}
if [ $# -gt 1 ]; then
  usage
  exit 1
fi

if [ $# -eq 1 ]; then
  file=$1
  if [ ! -f $file ]; then
    echo "File $file doesn't exist"
    usage
    exit 1
  fi
fi
awk -f $dir/summary.awk $*

