#!/bin/bash
#
# list livebox deconnections date time
#
dir=`dirname $0`
usage() {
  name=`basename "$0"`
  cat << EOF
usage: $name [-o] [filename]

This script returns the deconnection times as stored in the log file.

-o:  also display offline information

If filename isn't specified, it uses the standard input as input (cat filename | $name)
EOF
}
DEBUG=
while getopts “o” OPTION
do
     case $OPTION in
         o)
             DEBUG=true
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

if [ $# -ge $OPTIND ]; then
  shift $((OPTIND-1))
fi

if [ $# -gt 1 ]; then
  usage
  exit 1
fi

if [ $# -eq 1 ]; then
  file=$1
  if [ ! -f $file ]; then
    echo "File $file doesn't exist"
    usage
    exit 1
  fi
fi
export AWKPATH=$dir:$AWKPATH
if [ -z $DEBUG ]; then
  igawk -f $dir/summary.awk $*
else
  igawk -f $dir/summary.awk $* | igawk -f $dir/offline.awk
fi

